# Generated by Django 4.1 on 2022-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report1", models.BooleanField(default=True)),
                ("report2", models.BooleanField(default=False)),
                ("report3", models.BooleanField(default=False)),
                ("report4", models.BooleanField(default=False)),
                ("report5", models.BooleanField(default=False)),
                ("report6", models.BooleanField(default=False)),
                ("report7", models.BooleanField(default=False)),
                ("report8", models.BooleanField(default=False)),
            ],
        ),
    ]
