# Generated by Django 4.1 on 2022-08-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_collegeusers_project"),
        ("teachers", "0002_reportparts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
                ("mark", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(auto_now=True)),
                ("is_submit", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.collegeusers",
                    ),
                ),
            ],
        ),
    ]
