# Generated by Django 4.1 on 2022-08-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_rename_final_report_finalreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalreport",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
