# Generated by Django 4.1 on 2022-08-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_alter_project_number_of_students"),
        ("teachers", "0006_finalreport_is_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalreport",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="administration.project",
            ),
        ),
    ]
