# Generated by Django 4.1 on 2022-08-24 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("web", "تحت وب"),
                            ("desktop", "دسکتاپ"),
                            ("mobile", "موبایل"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "number_of_students",
                    models.IntegerField(
                        choices=[("one", "یک"), ("two", "دو"), ("three", "سه")]
                    ),
                ),
                ("description", models.TextField()),
                ("is_suggested", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
