# Generated by Django 4.1 on 2022-08-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number_of_students",
            field=models.IntegerField(choices=[(1, "یک"), (2, "دو"), (3, "سه")]),
        ),
    ]
